name: Unix Build

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

permissions:
  contents: read

env:
  artifacts: |
    me7sum
    ME7Check_linux
    README.md

jobs:
  build:
    strategy:
      matrix:
        os: [ 'ubuntu', 'macos']
    runs-on: ${{ matrix.os }}-latest
    env:
      HAS_CORPUS: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
    steps:
    - uses: actions/checkout@v7
    - if: env.HAS_CORPUS == 'true'
      uses: ./.github/actions/fetch-corpus
      with:
        client-id: ${{ vars.CORPUS_APP_CLIENT_ID }}
        private-key: ${{ secrets.CORPUS_APP_KEY }}
    - name: make
      run: make
    - name: make test
      run: make test
    - uses: rlespinasse/github-slug-action@v5
      id: slug
      with:
        short-length: 6
    - uses: actions/upload-artifact@v7
      with:
        name: me7sum-${{ steps.slug.outputs.GITHUB_SHA_SHORT }}-${{ matrix.os }}
        path: ${{ env.artifacts }}
