name: Unix Build

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  artifacts: |
    me7sum
    ME7Check_linux
    README.md

jobs:
  build:
    strategy:
      matrix:
        os: [ 'ubuntu', 'macos']
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v6
    - name: make
      run: make
    - name: make test
      run: make test
    - uses: rlespinasse/github-slug-action@v5
      id: slug
      with:
        short-length: 6
    - uses: actions/upload-artifact@v6
      with:
        name: me7sum-${{ steps.slug.outputs.GITHUB_SHA_SHORT }}-${{ matrix.os }}
        path: ${{ env.artifacts }}
