name: Windows Build

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  artifacts: |
    me7sum.exe
    ME7Check.exe
    README.md

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6
    - uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: x86
    - name: build
      run: nmake
    - uses: rlespinasse/github-slug-action@v5
      id: slug
      with:
        short-length: 6
    - uses: actions/upload-artifact@v6
      with:
        name: me7sum-${{ steps.slug.outputs.GITHUB_SHA_SHORT }}-win
        path: ${{ env.artifacts }}
